
[package]
name = "oneil_module"
description = "Modules for the Oneil programming language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oneil_ast = { path = "../oneil_ast" }
